# Generated by Django 5.1.6 on 2025-02-21 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسمك')),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقمك')),
                ('address', models.CharField(blank=True, choices=[('خارج سوريا', 'خارج سوريا'), ('ادلب', 'ادلب'), ('دمشق', 'دمشق'), ('حلب', 'حلب'), ('ريف دمشق', 'ريف دمشق'), ('حماه', 'حماه'), ('حمص', 'حمص'), ('درعا', 'درعا'), ('القنيطرة', 'القنيطرة'), ('السويداء', 'السويداء'), ('دير الزور', 'دير الزور'), ('القامشلي', 'القامشلي'), ('الحسكة', 'الحسكة'), ('اللاذقية', 'اللاذقية'), ('طرطوس', 'طرطوس')], max_length=30, null=True, verbose_name='المحافظة')),
                ('address_detail', models.CharField(blank=True, max_length=30, null=True, verbose_name='المدينة او البلدة')),
                ('type', models.CharField(blank=True, choices=[('مزرعة', 'مزرعة'), ('فيلا', 'فيلا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d', verbose_name='الصورة')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسمك')),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقمك')),
                ('us', models.CharField(blank=True, max_length=20, null=True, verbose_name='من اين سمعت عنا ؟')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='محافظتك')),
                ('birth', models.IntegerField(blank=True, null=True, verbose_name='عمرك')),
                ('un_booked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.newrealestate', verbose_name='طلبات لنشر عقار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('مزرعة', 'مزرعة'), ('فيلا', 'فيلا'), ('شقة', 'شقة')], max_length=30, null=True, verbose_name='نوع العقار')),
                ('address_detail2', models.TextField(blank=True, max_length=30, null=True, verbose_name='العنوان بالتفصيل (اسم الحارة والشارع)')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='السعر')),
                ('main_image', models.ImageField(default='photos/25/01/10/Prépare_tes_vacances.jpg', upload_to='photos/%y/%m/%d', verbose_name='الصورة')),
                ('time', models.CharField(blank=True, choices=[('بالليلة', 'بالليلة'), ('بالشهر', 'بالشهر')], max_length=30, null=True, verbose_name='اقل مدة زمنية لحجز العقار')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('average_rating', models.FloatField(default=0)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.city', verbose_name='المحافظة')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person', verbose_name='صاحب العقار')),
                ('Images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.realestate_images', verbose_name='صور العقار')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='home.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='MyReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.person', verbose_name='صاحب العقار')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to='home.realestate', verbose_name='العقار')),
            ],
        ),
        migrations.CreateModel(
            name='Favourits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='home.person', verbose_name='الزبون')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_list', to='home.realestate', verbose_name='العقار')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.realestate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.city')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.town', verbose_name='المدينة او البلدة'),
        ),
    ]
